version: '3.9'
services:

    postgres:
        image: "postgres:17.5-alpine"
        environment:
            - POSTGRES_DB=${POSTGRES_NAME}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASS}
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "${POSTGRES_PORT}:${POSTGRES_PORT_INNER}" 
        networks:
            - app-network
        restart: unless-stopped       

    app:
        build: .
        ports:
          - "${GCNTNR_PORT}:${GCNTNR_PORT}"
        environment:
          - POSTGRES_HOST=${POSTGRES_HOST}
          - POSTGRES_PORT=${POSTGRES_PORT_INNER}
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASS}
          - POSTGRES_NAME=${POSTGRES_NAME}
          - POSTGRES_SSLMODE=disable 
          - GCNTNR_PORT=${GCNTNR_PORT}
          - DEFAULT_ADMIN_ROLE_ID=${DEFAULT_ADMIN_ROLE_ID}
          - DEFAULT_USER_ROLE_ID=${DEFAULT_USER_ROLE_ID}
        depends_on:
          - postgres
        networks:
          - app-network
        restart: unless-stopped    
       
        
        
networks:
  app-network:
    driver: bridge     